### ISSUE TITLE
Yubico references

### ISSUE THREAD

**Issue by redDwarf03** [canokeys/canokey-management-tool#1]
Hello
in https://github.com/canokeys/canokey-management-tool/blob/e045b3714c1d0502212b434355021eac5b67ac14/lib/components/openpgp.dart#L667
you have referenced Yubico (I think VID=0x2C97 too).
is it possible to use your libs to interact with Yubikeys ?
Thx

**Comment by dangfan** [comment]
Unfortunately, in the current version (which runs on WebUSB), it will not work. However, you may notice that we're using `flutter_nfc_kit` to interact with tokens. As a result, after adding the Android and iOS variants of this app, using NFC is a possible way to interact with Yubikeys.

**Comment by redDwarf03** [comment]
Thx
